### ISSUE TITLE
[Actions] ブランチ・CI/CD構成案

### ISSUE THREAD

**Issue by sanak** [OSGeo-jp/OSGeoLive-doc#2]
@miurahr
現状、OSGeoLive-doc側では、下記のブランチ・CI/CD構成を考えていますが、私の方、CI/CDの経験がそれほどないため、ご意見頂けますと助かります。

## ブランチ・CI/CD構成

1. `master`
   - Upstreamとの同期用
   - 原文となる `*.rst` ファイル、`*.pot` ファイルで修正が入った場合に、以下の `transifex_ja` => `omegat_ja` の順にマージ
   - 同期作業は、現時点では手作業を想定
   - [CI/CD] `master` ブランチへのpushで、`gh-pages` への自動デプロイは対応済み (Webサイト: https://osgeo-jp.github.io/OSGeoLive-doc)
2. `transifex_ja`
   - TransifexのPull/Push管理用
   - CI/CD実行用に、TransifexのBotアカウントを作成する必要あり
   - [CI/CD] `transifex_ja` ブランチへのpushで、gh-pages への自動デプロイは対応済み (Webサイト: https://osgeo-jp.github.io/OSGeoLive-doc)
   - [CI/CD] Transifexからの最新の訳文のPull、コミット
      - 手順は https://github.com/OSGeo-jp/OSGeoLive-doc/wiki#fetchpush-latest-japanese-po-files と同様となる見込み
   - [CI/CD] TransifexへのOmegaTからの訳文更新分マージ => 差分をTransifexへPush
      - OmegaTからの訳文更新分を、 `transifex_ja` ブランチに対するPullRequestの形で作成しておき、担当者がPRの差分を目視で確認の上、手動でTransifexへのPushをトリガーできることが望ましい (以下の `omegat_ja` ブランチから本ブランチへのPullRequestを手動トリガーで作成する形が無難？)
3. `omegat_ja`
   - `OSGeoLive-doc-omegat` リポジトリとの同期用
   - 原文更新時は、 `master` => `transifex_ja` => `omegat_ja` ブランチへマージ
   - 訳文更新時は、 `OSGeoLive-doc-omegat` 側のCI/CD内で、 `OSGeoLive-doc/omegat_ja` ブランチをチェックアウトし、訳文生成した `target` フォルダ内のpoファイルを、 `locale/ja/LC_MESSAGES` フォルダ配下に上書き、git add/commit後、git push で 直接更新
   - [CI/CD] `omegat_ja` ブランチへのpushで、gh-pages への自動デプロイは対応済み (Webサイト: https://osgeo-jp.github.io/OSGeoLive-doc)

※Webサイト(https://osgeo-jp.github.io/OSGeoLive-doc) への反映は、上記各ブランチへのpush時に反映されます。

**Comment by miurahr** [comment]
OmegaTプロジェクトのsourceへの取り込みは、手動ではなく、 本リポジトリへのマッピングで実現してはどうでしょうか。
sourceの更新は、本リポジトリの更新で実現する。 `OSGeoLive-doc-omegat` リポジトリからは、sourceを削除する。

**Comment by sanak** [comment]
@miurahr 上記提案、ありがとうございます。
`OSGeoLive-doc-omegat` 側で作成頂いたActions(`check`)の方で、動作・実行時間的に問題なさそうであれば、確かにその方が良いかもしれません。

**Comment by miurahr** [comment]
omegatのソースマッピングで原文取得を自動化するなら、 transifex_ja からひっぱってきてもいいのではないか。 むしろ最新が反映されてよいのではないか？
マッピング提案は以下です。omegat_jaブランチを参照しています。
https://github.com/OSGeo-jp/OSGeoLive-doc-omegat/pull/9

**Comment by sanak** [comment]
@miurahr 迅速な対応ありがとうございます！
確かに `transifex_ja` から引っ張ってくる方が良いかもしれません。

Actionsの実行時間も2分半ほどで、OmegaTの自動保存間隔のデフォルト3分に収まっているので問題ないように思いました。
https://github.com/miurahr/OSGeoLive-doc-omegat/actions/runs/434640652

**Comment by miurahr** [comment]
> Actionsの実行時間も2分半ほどで、OmegaTの自動保存間隔のデフォルト3分に収まっているので問題ないように思いました。

複数名が作業していると、もっと高頻度になるので、できれば、30分に一回とか、リミットがあるといいんですけどね。

**Comment by miurahr** [comment]
Actionsで、キャッシュをつかうようにして、実行時間を1分強にしました。 sourceをリポジトリからひっぱってくる時間とpip installで50秒くらいかかっていて、正味の時間は20秒くらいです。

**Comment by miurahr** [comment]
OmegaTは、"master"ブランチにしか対応していないため、 SubVersionのブランチ指定と、GithubのSVNインタフェースを利用しています。GithubのSVN互換は性能制限があるため、時間がかかるというわけです。

**Comment by sanak** [comment]
@miurahr 上記、返信が遅くなりましたが、対応ありがとうございました :bow:
下記は、私の方で少し確認してみます。
> 訳文更新時は、 OSGeoLive-doc-omegat 側のCI/CD内で、 OSGeoLive-doc/omegat_ja ブランチをチェックアウトし、訳文生成した target フォルダ内のpoファイルを、 locale/ja/LC_MESSAGES フォルダ配下に上書き、git add/commit後、git push で 直接更新

**Comment by sanak** [comment]
上記の `OSGeoLive-doc-omegat`(以下`omegat`) => `OSGeoLive-doc` の `omegat_ja` ブランチ(以下`doc`)の更新について色々とググってみたんですが、GitHub Actionsでリポジトリ間の連携を行う場合、
1. `omegat` => `doc` へのpushを直接行う場合は、push先(`doc`側)でDeploy keyを設定し、push元(`omegat`側)でSecretsにSSH秘密鍵を登録する必要がある見込み。
   - [GitHub Actions で別のリポジトリに git push する](https://3nan3.github.io/post/2019122201_github_actions/)
   - [Push from action to different remote repo - Code to Cloud / GitHub Actions - GitHub Support Community](https://github.community/t/push-from-action-to-different-remote-repo/17848)
   - [GitHub ActionsでSSHを使う - Qiita](https://qiita.com/shimataro999/items/b05a251c93fe6843cc16)
2. `omegat`側でイベントのみ通知し、 `doc` 側でイベントを検知してpullする場合は、 `doc` 側で `workflow_dispatch` もしくは `repository_dispatch` イベントに対応したワークフローを定義しておき、イベント発行(`omegat`)側では、個人アクセストークンを利用して、GitHubのRest APIにPOSTする必要がある見込み。
   - [Github Actions で他のリポジトリからの変更通知を受け取ってPRを作成する Workflow](https://zenn.dev/mizchi/articles/3117b92a834531361fc8)
   - [Triggering by other repository - Code to Cloud / GitHub Actions - GitHub Support Community](https://github.community/t/triggering-by-other-repository/16163/6)

GitHub上でそれぞれのリポジトリがフォークされた際の動作も考えると、なるべく疎結合とした方が良いように思いましたので、一旦、No.2の方向で検討します。

**Comment by miurahr** [comment]
そんなに頻繁に更新したいわけではない、とおもいますので、たとえば日に1回、アクションをdoc側で実行する。
```
 on:
  schedule:
  - cron: "0 0 * * *"
```

1. omegat側をチェックアウトして、   `actions/checkout@v2` 
2. omegat/*.tmxのgit変更履歴をみて、 `git log --pretty=format: --name-only --since="1 day ago"`
3. もし24時間以内に更新があるなら  (2)の出力があった場合となり、
4. 訳文を生成してLOCALE/以下の更新をかけてみる。
5. もしPOファイルの変更が発生したらPRを作成する。 `git status --porcelain` の出力の有無、
4. そうでなければ、変更なし。

というワークフローも考えられます。これを日次でもいいですし、週次でもいいとおもいます。

**Comment by sanak** [comment]
@miurahr 
アドバイス、ありがとうございます。
日に一度の実行をベースにする点については、確かにその方が良さそうに思いました。
4.の訳文の生成の箇所が、`omegat`側でできる(=`target`フォルダに格納しておく？)と、`doc`側で`omegat`側のロジックを含めずに済み、良さそうに思いましたので、もう少し、手元で動作を確認を進めていくようにします。

**Comment by miurahr** [comment]
doc側には、omegat側のロジック？は不要です。というのは、チェックアウトするからです。
doc側のgithub actionsでの追加は、Javaを追加し、omegat側のロジックの呼び出しをするだけです。

**Comment by sanak** [comment]
@miurahr なるほど、了解です。
(GitHub Actionsについて、私の方で少し複雑に考えすぎていたかもしれません...。)
一旦、アドバイス頂いた方法をベースに、`doc`側での実装を検討してみます。
(日次+手動(workflow_dispatch)ベースで、一部Marketplace上のアクションなどで代用するかもしれません...。:bow: )

**Comment by sanak** [comment]
こちら、説明欄に記載の運用方法は現状できていますので、一旦クローズします。
