### ISSUE TITLE
Transifexで原文が更新されたときに、本リポジトリの更新が不足している

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc#24]
quickstart/pgrouting_quickstart,  quickstart/osm_quickstart, quickstart/mapnik_quickstartなどが、1月19日に原文更新されているが、本リポジトリに反映されていないようにみえる。

modeオプションが必要

```
--mode [developer | translator| ...]
```

developer: The files downloaded will be compatible with the i18n support of the development framework you’re using. This is the default mode when you run tx pull. Use this mode when you intend to use the file e.g. in production. This mode auto-fills empty translations with the source language text for most of the file formats we support, which is critical in the case of file formats that require all translations to be non-empty.

translator: The files will be suitable for offline translation. Equivalent to the web app's option "Download file to translate" (for_translation).

既定では、developerモードであり、未翻訳の用語の処理がTranslatorモードとちがう

**Comment by miurahr** [comment]
cf. https://docs.transifex.com/client/pull/

**Comment by sanak** [comment]
mapnik_quickstartは、1/19分は下記コミットで更新されているようでした。(私の方で昨晩、OmegaTの翻訳の方も更新しました。)
- `transifex_ja`: https://github.com/OSGeo-jp/OSGeoLive-doc/commit/def4e8fa90bcdbc64cb60d400a31fa3aee145aa9
- `omegat_ja`: https://github.com/OSGeo-jp/OSGeoLive-doc/commit/56136451cf80b3377e05c27d6bfe1b5395105a6a

pgrouting_quickstartは日本時間0時以降に更新がかかったようなので、一度Pull Transifexを手動で実行してみます。

モードの件も、情報ありがとうございます。 :bow:

**Comment by sanak** [comment]
手動のPull Transifex実行で、pgrouting_quickstart と osm_quickstart、および mapnik_quickstart の追加更新分も反映されたようです。
- `transifex_ja`: https://github.com/OSGeo-jp/OSGeoLive-doc/commit/c4dacc1b5fcd09fc1502a623071ddde52051b947
- `omegat_ja`: https://github.com/OSGeo-jp/OSGeoLive-doc/commit/661880a1a0fb91441978d35244a391d086ad8981

**Comment by sanak** [comment]
commandline_quickstart が追加されたようですが、upstreamのmasterブランチから .tx/config を手動で transifex_ja・omegat_jaにmergeする必要があるので、こちらは今晩以降の対応になると思います。

**Comment by sanak** [comment]
こちら、今のところ問題なさそうなので、クローズします。
