### ISSUE TITLE
OSGeoLive14.0 (Beta1)でUIの翻訳相違をチェックする

### ISSUE THREAD

**Issue by miurahr** [OSGeo-jp/OSGeoLive-doc#26]
https://www.mail-archive.com/osgeolive@lists.osgeo.org/msg02072.html

OSGeoLive 14.0 Beta1のISOがダウンロード可能なので、その実行イメージで、UIの一貫性や整合性をチェックするとよい。

**Comment by miurahr** [comment]
メニューにおいて、日本語になっているのは、「QGISデスクトップ」のみ。

![VirtualBox_osgeo-live_06_02_2021_16_55_03](https://user-images.githubusercontent.com/123720/107112596-1e736d00-689c-11eb-9f77-b84c90bf9cbc.png)

**Comment by sanak** [comment]
@miurahr  
はい。  
あくまで推測ですが、新しいデスクトップ環境のLXQt がQtベースで、QGISもQtベースなので、デスクトップ環境側で自動的に認識しているのでは...と考えています。

**Comment by sanak** [comment]
2/17~19 (EST時間)開催のOGC/OSGeo/ApacheSoftwareFoundationのCode Sprint(https://github.com/opengeospatial/joint-ogc-osgeo-asf-sprint-2021) の一環で、先ほど、beta3がリリースされたようでしたので、念のため、リンクを貼っておきます。
- https://lists.osgeo.org/pipermail/discuss/2021-February/039239.html

**Comment by miurahr** [comment]
QGISのバージョンがあがっているではないですか。QGISのアプリの翻訳はどうなっているんだろう？

**Comment by miurahr** [comment]
14.0がリリース
